openapi: 3.0.3
info:
  title: Master Details redactor test
  version: 1.0.0
  description: Тестовый проект
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /create_document:
    get:
      responses:
        '200':
          description: Success

components:
  schemas:
    Test:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string