openapi: 3.0.3
info:
  title: Master Details redactor test
  version: 1.0.0
  description: Тестовый проект
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /create_document/add_document:
    post:
      operationId: addMaster
      parameters:
        - name:
          in: query
          description:
          required: true
          schema:
            type: integer
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/delete_document:
    post:
      operationId: deleteMaster
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/change_document:
    post:
      operationId: changeMaster
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/add_specific:
    post:
      operationId: addDetail
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/delete_specific:
    post:
      operationId: deleteDetail
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/change_specific:
    post:
      operationId: changeDetail
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'

components:
  schemas:
    Document:
      type: object
      properties:
        docNumber:
          type: integer
        docDate:
          type: string
        Comment:
          type: string
    Specifications:
      type: object
      properties:
        docId:
          type: integer
        name:
          type: string
        amount:
          type: integer

    EditResult:
      required:
        - message
        - success
      type: object
      properties:
        success:
          type: boolean
          description: Успешность выполнения
          example: false
        message:
          type: string
          description: Сообщение
      description: Результат работы