openapi: 3.0.3
info:
  title: Master Details redactor test
  version: 1.0.0
  description: Тестовый проект
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /create_document/add_document:
    post:
      operationId: addMaster
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
        - name: docDate
          in: query
          description: Дата документа
          required: false
          schema:
            type: string
        - name: comment
          in: query
          description: Комментарий
          required: false
          schema:
            type: integer
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/delete_document:
    post:
      operationId: deleteMaster
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/change_document:
    post:
      operationId: changeMaster
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
        - name: newDocId
          in: query
          description: Новый номер
          required: true
          schema:
            type: string
        - name: docDate
          in: query
          description: Новая дата документа
          required: false
          schema:
            type: string
        - name: comment
          in: query
          description: Новый комментарий
          required: false
          schema:
            type: integer
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/add_specific:
    post:
      operationId: addDetail
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
        - name: name
          in: query
          description: Название специфики
          required: true
          schema:
            type: string
        - name: ammount
          in: query
          description: Сумма специфики
          required: true
          schema:
            type: integer
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/delete_specific:
    post:
      operationId: deleteDetail
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
        - name: name
          in: query
          description: Название специфики
          required: true
          schema:
            type: string
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/change_specific:
    post:
      operationId: changeDetail
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
        - name: name
          in: query
          description: Название специфики
          required: true
          schema:
            type: string
        - name: newName
          in: query
          description: Новое название специфики
          required: true
          schema:
            type: string
        - name: ammount
          in: query
          description: Новая сумма специфики
          required: true
          schema:
            type: integer
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'

components:
  schemas:
    Document:
      type: object
      properties:
        docNumber:
          type: string
        docDate:
          type: string
        Comment:
          type: string
    Specifications:
      type: object
      properties:
        docNumber:
          type: string
        name:
          type: string
        amount:
          type: integer

    EditResult:
      required:
        - message
        - success
      type: object
      properties:
        success:
          type: boolean
          description: Успешность выполнения
          example: false
        message:
          type: string
          description: Сообщение
      description: Результат работы