openapi: 3.0.3
info:
  title: Master Details redactor test
  version: 1.0.0
  description: Тестовый проект
servers:
  - url: http://localhost:8080
    description: Local server
paths:
components:
  schemas: