openapi: 3.0.3
info:
  title: Master Details redactor test
  version: 1.0.0
  description: Тестовый проект
servers:
  - url: "mdrt-test/api"
    description: Local server

paths:
  /create_document/add_document:
    post:
      operationId: addMaster
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
        - name: docDate
          in: query
          description: Дата документа. Формат - гггг-мм-дд
          required: false
          schema:
            type: string
            format: date
        - name: comment
          in: query
          description: Комментарий
          required: false
          schema:
            type: string
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/delete_document:
    post:
      operationId: deleteMaster
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/change_document:
    post:
      operationId: changeMaster
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
        - name: newDocId
          in: query
          description: Новый номер
          required: true
          schema:
            type: string
        - name: docDate
          in: query
          description: Новая дата документа. Формат - гггг-мм-дд
          required: false
          schema:
            type: string
            format: date
        - name: comment
          in: query
          description: Новый комментарий
          required: false
          schema:
            type: string
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/add_specific:
    post:
      operationId: addDetail
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
        - name: name
          in: query
          description: Название специфики
          required: true
          schema:
            type: string
        - name: ammount
          in: query
          description: Сумма специфики
          required: true
          schema:
            type: integer
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/delete_specific:
    post:
      operationId: deleteDetail
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
        - name: name
          in: query
          description: Название специфики
          required: true
          schema:
            type: string
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/change_specific:
    post:
      operationId: changeDetail
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
        - name: name
          in: query
          description: Название специфики
          required: true
          schema:
            type: string
        - name: newName
          in: query
          description: Новое название специфики
          required: true
          schema:
            type: string
        - name: ammount
          in: query
          description: Новая сумма специфики
          required: true
          schema:
            type: integer
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditResult'
  /create_document/get_documents:
    get:
      operationId: getMaster
      responses:
        200:
          description: Список документов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
  /create_document/get_specific:
    get:
      operationId: getDetail
      parameters:
        - name: docId
          in: query
          description: id документа
          required: true
          schema:
            type: string
      responses:
        200:
          description: Список спецификаций документа
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Specifications'
  /create_document/get_logs:
    get:
      operationId: getLog
      responses:
        200:
          description: Логи оперций с документами
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LogMD'

components:
  schemas:
    Document:
      type: object
      properties:
        docNumber:
          description: Номер документа
          type: string
        docDate:
          description: Дата документа
          type: string
          format: date
        totalAmount:
          description: Сумма документа
          type: integer
        Comment:
          description: Примечание
          type: string

    Specifications:
      type: object
      properties:
        docNumber:
          description: Номер документа
          type: string
        name:
          description: Имя спецификации
          type: string
        amount:
          description: Сумма спецификации
          type: integer

    LogMD:
      type: object
      properties:
        tableName:
          description: Название таблицы БД
          type: string
        succsess:
          description: Код ошибки
          type: integer
        message:
          description: Сообщение
          type: string
        timestamp:
          description: Время записи
          type: string
          format: date-time
        recordData:
          description: Параметры операции
          type: string


    EditResult:
      required:
        - message
        - success
      type: object
      properties:
        success:
          type: boolean
          description: Успешность выполнения
          example: false
        message:
          type: string
          description: Сообщение
      description: Результат работы