openapi: 3.0.3
info:
  title: Master Details redactor test
  version: 1.0.0
  description: Тестовый проект
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /create_document/add_document:
    get:
      operationId: addMaster
      responses:
        200:
          description: Success
  /create_document/delete_document:
    get:
      operationId: deleteMaster
      responses:
        200:
          description: Success
  /create_document/change_document:
    get:
      operationId: changeMaster
      responses:
        200:
          description: Success
  /create_document/add_specific:
    get:
      operationId: addDetail
      responses:
        200:
          description: Success
  /create_document/delete_specific:
    get:
      operationId: deleteDetail
      responses:
        200:
          description: Success
  /create_document/change_specific:
    get:
      operationId: changeDetail
      responses:
        200:
          description: Success

components:
  schemas:
    Document:
      type: object
      properties:
        docNumber:
          type: integer
        docDate:
          type: string
        Comment:
          type: string
    Specifications:
      type: object
      properties:
        docId:
          type: integer
        name:
          type: string
        amount:
          type: integer